


run-ncurses-animation:
	cd ../../../..; \
	podman exec -it -w /work/$$(basename $$(pwd))/_build/debug -e LANG=en_US_UTF-8 -e LC_ALL=en_US.UTF-8 \
	    gcc14-tools bin/ncurses-animation


run-ncurses-animation-color:
	cd ../../../..; \
	podman exec -it -w /work/$$(basename $$(pwd))/_build/debug -e LANG=en_US_UTF-8 -e LC_ALL=en_US.UTF-8 \
	    gcc14-tools bin/ncurses-animation-color


run-ncurses-snippet:
	cd ../../../..; \
	podman exec -it -w /work/$$(basename $$(pwd))/_build/debug -e LANG=en_US_UTF-8 -e LC_ALL=en_US.UTF-8 \
	    gcc14-tools bin/ncurses-snippet

